import { StaticImageData } from "next/image";
import category1 from "../../public/Images/category_1.png";
import category2 from "../../public/Images/category_2.png";
import category3 from "../../public/Images/category_3.png";
import category4 from "../../public/Images/category_4.png";




export const categoryList:Array<Record<string,any>>=[
    {
        "id":"1",
        "isChecked":true,
        "name":"Single Detached",
        "products":[
         
            {
                "id":"singleD1",
                "name":"name",
                "img": category1,
                "heading": "Single Detached",
                "price": `$9.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"singleD2",
                "name":"name",
                "img": category2,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"singleD3",
                "name":"name",
                "img": category3,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"singleD4",
                "name":"name",
                "img": category4,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
        
        ],
    },
    {
        "id":"2",
        "isChecked":false,
        "name":"Semi Detached",
        "products":[
            {
                "id":"semiD1",
                "name":"name",
                "img": category4,
                "heading": " Semi Detached",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"semmiD2",
                "name":"name",
                "img": category3,
                "heading": " Semi Detached",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"semiD3",
                "name":"name",
                "img": category2,
                "heading": " Semi Detached",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
        
       
            {
                "id":"semiD4",
                "name":"name",
                "img": category1,
                "heading": " Semi Detached",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            
            {
                "id":"semiD5",
                "name":"name",
                "img": category1,
                "heading": " Semi Detached",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            
            {
                "id":"semiD6",
                "name":"name",
                "img": category1,
                "heading": " Semi Detached",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
          
        
        ],
    },
    {
        "id":"3",
        "isChecked":false,
        "name":"Acreage",
        "products":[
            {
                "id":"acr1",
                "name":"name",
                "img": category1,
                "heading": "Acreage",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"acr2",
                "name":"name",
                "img": category1,
                "heading": "Acreage",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"acr3",
                "name":"name",
                "img": category1,
                "heading": "Acreage",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"acr4",
                "name":"name",
                "img": category1,
                "heading": "Acreage",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
        ],
    },
    {
        "id":"4",
        "isChecked":false,
        "name":"Garage Suite",
        "products":[
            {
                "id":"gs1",
                "name":"name",
                "img": category1,
                "heading": "Garage Suite",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"gs2",
                "name":"name",
                "img": category1,
                "heading": "Garage Suite",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"gs3",
                "name":"name",
                "img": category1,
                "heading": "Garage Suite",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"gs4",
                "name":"name",
                "img": category1,
                "heading": "Garage Suite",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
      
           

        ],
    },
    {
        "id":"5",
        "isChecked":false,
        "name":"FourPlex",
        "products":[
            {
                "id":"FP1",
                "name":"name",
                "img": category1,
                "heading": "FourPLex",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"FP2",
                "name":"name",
                "img": category1,
                "heading": "FourPLex",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"FP3",
                "name":"name",
                "img": category1,
                "heading": "FourPLex",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"FP4",
                "name":"name",
                "img": category1,
                "heading": "FourPLex",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
      
           

        ],
    },
];
// export const CardData:Array<Data>=[
//     {
//         id: "1",
//         value:"1",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"1",
//         img: category2,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"1",
//         img: category3,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"1",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },

//       {
//         id: "1",
//         value:"2",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"2",
//         img: category1,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"2",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"2",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
 
//       {
//         id: "1",
//         value:"3",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"3",
//         img: category2,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"3",
//         img: category3,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"3",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "1",
//         value:"4",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"4",
//         img: category2,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"4",
//         img: category3,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"4",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
 
     
// ];