import { StaticImageData } from "next/image";
import category1 from "../../public/Images/category_1.png";
import category2 from "../../public/Images/category_2.png";
import category3 from "../../public/Images/category_3.png";
import category4 from "../../public/Images/category_4.png";




export const categoryList:Array<Record<string,any>>=[
    {
        "id":"1",
        "name":"Single Detached",
        "products":[
            {
                "id":"1",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 2",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 3",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 4",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
        
        ],
    },
    {
        "id":"2",
        "name":"Semi Detached",
        "products":[
            {
                "id":"product 1",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 2",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 3",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 4",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
          
        
        ],
    },
    {
        "id":"3",
        "name":"Acreage",
        "products":[
            {
                "id":"product 1",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 2",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 3",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 4",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
        ],
    },
    {
        "id":"4",
        "name":"Garage Suite",
        "products":[
            {
                "id":"product 1",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 2",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 3",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
            {
                "id":"product 4",
                "name":"name",
                "img": category1,
                "heading": "In laoreet magna sit",
                "price": `$69.00`,
                "title1": "eiusmod tempo",
                "title2": "eiusmod tempo",
                "titleText1": "eiusmod",
                "titleText2": "eiusmod",
            },
           

        ],
    },
];
// export const CardData:Array<Data>=[
//     {
//         id: "1",
//         value:"1",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"1",
//         img: category2,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"1",
//         img: category3,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"1",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },

//       {
//         id: "1",
//         value:"2",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"2",
//         img: category1,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"2",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"2",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
 
//       {
//         id: "1",
//         value:"3",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"3",
//         img: category2,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"3",
//         img: category3,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"3",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "1",
//         value:"4",
//         img: category1,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "2",
//         value:"4",
//         img: category2,
//         heading: "Etiam pellentesque mi ut tellus",
//         price: `$45.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "3",
//         value:"4",
//         img: category3,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
//       {
//         id: "4",
//         value:"4",
//         img: category4,
//         heading: "In laoreet magna sit",
//         price: `$69.00`,
//         title1: "eiusmod tempo",
//         title2: "eiusmod tempo",
//         titleText1: "eiusmod",
//         titleText2: "eiusmod",
//       },
 
     
// ];